### ISSUE TITLE
Split package up into 2/3 separate packages 

### ISSUE THREAD

**Issue by mikemhenry** [choderalab/covid-moonshot-ml#23]
There seems to be 3 main uses for this code:
1. Dataset download/cleaning
2. ML stuff
3. Docking stuff

For 1, we could put that in the ML stuff or the docking stuff, but given the separate dependencies it may be best to have the dataset stuff as its own package.

Given that while there are three separate foci, the packages are used together and very related. I think what we should do is use this single repository for three packages. That way development that requires changes in say 1 & 2 can be done in a single PR without having to coordinate across two repositories.

First, we need to get https://github.com/choderalab/covid-moonshot-ml/pull/21 merged in 

Checklist:
 * Phase one:
   - [x] https://github.com/choderalab/covid-moonshot-ml/pull/21
 * Phase two:
   - [x] Identify how to split code into three separate packages
   - [x] Come up with three good names
   - [ ] Split up package in a single PR.

**Comment by dotsdl** [comment]
@mikemhenry I agree with your assessment. I propose that we turn this repo into `comp-chem-asap`, since it will feature components specific to the ASAP Computational Chemistry effort. Some of the components that are built out may generalize and be spun out into other packages, but it is unclear *a priori* which components those will be until we have a pipeline we are running in production with.

It looks like it already is separated fairly well into the three areas of concern you've identified. There is also some overlap of this package with [`fah-xchem`](https://github.com/choderalab/fah-xchem), in particular pulling from relevant data systems:
-  CDD interface, perhaps more general: https://github.com/choderalab/fah-xchem/blob/master/fah_xchem/external/cdd.py
- Fragalysis interface: https://github.com/choderalab/fah-xchem/blob/master/fah_xchem/external/fragalysis.py

Expanding the repertoire of functionality for CDD and Fragalysis interfaces can be a separate PR once we've got this split.

**Comment by jchodera** [comment]
>  I propose that we turn this repo into comp-chem-asap, since it will feature components specific to the ASAP Computational Chemistry effort.

We have a few options regarding renaming:
* If these tools are specific to the ASAP computational chemistry effort (or potentially significantly in service of them), we can migrate to https://github.com/asapdiscovery
* Instead of `comp-chem-asap`, perhaps `asap-compchem` or `asap-modeling`? Another possibility would be to have module names without hyphens or understrikes so there is a 1:1 correspondence between package and module names, such as `asapmodel` or `asapcompchem`. `asapred`?

**Comment by dotsdl** [comment]
Proposal: let's proceed with `asapdiscover` as a namespace package, with this repo renamed to `asapdiscover`. Then the individual modules that @mikemhenry described above and @apayne97, @kaminow have articulated could be:
- `asapdiscover.io` or `asapdiscover.data` : download/upload to/from ASAP data systems, such as CDD Vault, Fragalysis, PostEra, PDB
- `asapdiscover.docking` : docking pipeline library code
- `asapdiscover.ml` : machine-learning components

These could be distributed as separate `conda` packages, similar to how OpenFF does this, or could be packaged all together. This approach does not preclude creation of other repos with other packages in the same `asapdiscover` namespace later.

Thoughts? If there are no objections, I'd like us to proceed.
